baseURL = 'https://martinsplitt.photo/'
languageCode = 'en-us'
title = 'Martin Splitt Photography'
copyright = "© Martin Splitt"
timeZone = "Europe/Berlin"
timeout = "120"

[params]
    defaultTheme = "dark"
    description = "Landscape and aerial photography"
    watermark = "images/logo.png"
    [params.author]
        name = "Martin Splitt"
    [params.socialIcons]
        instagram = "https://instagram.com/the_splitti"

[module]
  [[module.imports]]
    path = "github.com/avgp/hugo-theme-gallery"